<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <!-- ILRepack -->
  <PropertyGroup>
    <ILRepackOutputFile>$(OutputPath)\$(TargetFileName)</ILRepackOutputFile>
    <ILRepackLibraryPath>$(OutputPath)</ILRepackLibraryPath>
  </PropertyGroup>

  <Target Name="ILRepacker" AfterTargets="Build">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\$(TargetFileName)" />
      <InputAssemblies Include="$(OutputPath)\HighResolutionTimer.dll" />
    </ItemGroup>

    <ItemGroup>
      <!-- Must be a fully qualified name -->
      <!-- <DoNotInternalizeAssemblies Include="ExampleAssemblyToMerge3" /> -->
    </ItemGroup>

    <ILRepack
      Parallel="true"
      Internalize="true"
      LibraryPath="$(ILRepackLibraryPath)"
      InputAssemblies="@(InputAssemblies)"
      TargetKind="Dll"
      OutputFile="$(OutputPath)\$(AssemblyName).dll" />
  </Target>
  <!-- /ILRepack -->
</Project>